version: "3"
services:
  mongo-db:
    image: mongo:4.2
    container_name: "java-mongodb-sp-db"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME:-topcoder}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD:-Topcoder123}
    ports:
      - "27017:27017"
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    image: java-mongo-sp-api
    container_name: "java-mongo-sp-api"
    ports:
      - "8080:8080"
    restart: on-failure  
    links:
      - "mongo-db:database-host"  
    depends_on:
      - "mongo-db"